# Generated by Django 3.2.7 on 2021-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("consult_date", models.DateTimeField()),
                ("image", models.CharField(max_length=200)),
                ("store_url", models.CharField(max_length=200)),
                ("c", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
